<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Kapitel 15 ANOVA | Einführung in R</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Kapitel 15 ANOVA | Einführung in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Kapitel 15 ANOVA | Einführung in R" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Stephan Goerigk" />


<meta name="date" content="2023-04-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="einfache-hypothesentests.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R and der CFH</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="über-dieses-skript.html"><a href="über-dieses-skript.html"><i class="fa fa-check"></i>Über dieses Skript</a></li>
<li class="chapter" data-level="1" data-path="warum-ist-r-empfehlenswert.html"><a href="warum-ist-r-empfehlenswert.html"><i class="fa fa-check"></i><b>1</b> Warum ist R empfehlenswert?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="warum-ist-r-empfehlenswert.html"><a href="warum-ist-r-empfehlenswert.html#open-source"><i class="fa fa-check"></i><b>1.1</b> Open Source</a></li>
<li class="chapter" data-level="1.2" data-path="warum-ist-r-empfehlenswert.html"><a href="warum-ist-r-empfehlenswert.html#vielseitigkeit"><i class="fa fa-check"></i><b>1.2</b> Vielseitigkeit</a></li>
<li class="chapter" data-level="1.3" data-path="warum-ist-r-empfehlenswert.html"><a href="warum-ist-r-empfehlenswert.html#rmarkdown"><i class="fa fa-check"></i><b>1.3</b> RMarkdown</a></li>
<li class="chapter" data-level="1.4" data-path="warum-ist-r-empfehlenswert.html"><a href="warum-ist-r-empfehlenswert.html#transparenz"><i class="fa fa-check"></i><b>1.4</b> Transparenz</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-materialien.html"><a href="r-materialien.html"><i class="fa fa-check"></i><b>2</b> R Materialien</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-materialien.html"><a href="r-materialien.html#cheat-sheets"><i class="fa fa-check"></i><b>2.1</b> Cheat Sheets</a></li>
<li class="chapter" data-level="2.2" data-path="r-materialien.html"><a href="r-materialien.html#hilfe-und-inspiration-online"><i class="fa fa-check"></i><b>2.2</b> Hilfe und Inspiration online</a></li>
<li class="chapter" data-level="2.3" data-path="r-materialien.html"><a href="r-materialien.html#andere-bücher"><i class="fa fa-check"></i><b>2.3</b> Andere Bücher</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>3</b> Installation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="installation.html"><a href="installation.html#installation-von-r"><i class="fa fa-check"></i><b>3.1</b> Installation von R</a></li>
<li class="chapter" data-level="3.2" data-path="installation.html"><a href="installation.html#installation-von-rstudio"><i class="fa fa-check"></i><b>3.2</b> Installation von RStudio</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="programmaufbau.html"><a href="programmaufbau.html"><i class="fa fa-check"></i><b>4</b> Programmaufbau</a>
<ul>
<li class="chapter" data-level="4.1" data-path="programmaufbau.html"><a href="programmaufbau.html#die-vier-rstudio-fenster"><i class="fa fa-check"></i><b>4.1</b> Die vier RStudio Fenster</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="programmaufbau.html"><a href="programmaufbau.html#source---ihr-schreibblock-für-code"><i class="fa fa-check"></i><b>4.1.1</b> Source - Ihr Schreibblock für Code</a></li>
<li class="chapter" data-level="4.1.2" data-path="programmaufbau.html"><a href="programmaufbau.html#konsole---das-herzstück-von-r"><i class="fa fa-check"></i><b>4.1.2</b> Konsole - Das Herzstück von R</a></li>
<li class="chapter" data-level="4.1.3" data-path="programmaufbau.html"><a href="programmaufbau.html#environmenthistory---das-gedächtnis-von-r"><i class="fa fa-check"></i><b>4.1.3</b> Environment/History - Das Gedächtnis von R</a></li>
<li class="chapter" data-level="4.1.4" data-path="programmaufbau.html"><a href="programmaufbau.html#filesplotspackageshelpviewer---interaktion-von-r-mit-dateien"><i class="fa fa-check"></i><b>4.1.4</b> Files/Plots/Packages/Help/Viewer - Interaktion von R mit Dateien</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="programmaufbau.html"><a href="programmaufbau.html#r-packages"><i class="fa fa-check"></i><b>4.2</b> R Packages</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="programmaufbau.html"><a href="programmaufbau.html#r-packages-installieren"><i class="fa fa-check"></i><b>4.2.1</b> R Packages installieren</a></li>
<li class="chapter" data-level="4.2.2" data-path="programmaufbau.html"><a href="programmaufbau.html#r-packages-laden"><i class="fa fa-check"></i><b>4.2.2</b> R Packages laden</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="datenformate.html"><a href="datenformate.html"><i class="fa fa-check"></i><b>5</b> Datenformate</a>
<ul>
<li class="chapter" data-level="5.1" data-path="datenformate.html"><a href="datenformate.html#skalar"><i class="fa fa-check"></i><b>5.1</b> Skalar</a></li>
<li class="chapter" data-level="5.2" data-path="datenformate.html"><a href="datenformate.html#vektor"><i class="fa fa-check"></i><b>5.2</b> Vektor</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="datenformate.html"><a href="datenformate.html#vektor-typen"><i class="fa fa-check"></i><b>5.2.1</b> Vektor Typen</a></li>
<li class="chapter" data-level="5.2.2" data-path="datenformate.html"><a href="datenformate.html#faktor-variablen"><i class="fa fa-check"></i><b>5.2.2</b> Faktor Variablen</a></li>
<li class="chapter" data-level="5.2.3" data-path="datenformate.html"><a href="datenformate.html#vektor-indizierung"><i class="fa fa-check"></i><b>5.2.3</b> Vektor Indizierung</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="datenformate.html"><a href="datenformate.html#matrizen-und-data.frames"><i class="fa fa-check"></i><b>5.3</b> Matrizen und data.frames</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="datenformate.html"><a href="datenformate.html#erstellen-von-datenmatrizen"><i class="fa fa-check"></i><b>5.3.1</b> Erstellen von Datenmatrizen</a></li>
<li class="chapter" data-level="5.3.2" data-path="datenformate.html"><a href="datenformate.html#indizierung"><i class="fa fa-check"></i><b>5.3.2</b> Indizierung</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="daten-erstellen.html"><a href="daten-erstellen.html"><i class="fa fa-check"></i><b>6</b> Daten erstellen</a>
<ul>
<li class="chapter" data-level="6.1" data-path="daten-erstellen.html"><a href="daten-erstellen.html#manuell"><i class="fa fa-check"></i><b>6.1</b> Manuell</a></li>
<li class="chapter" data-level="6.2" data-path="daten-erstellen.html"><a href="daten-erstellen.html#automatisch"><i class="fa fa-check"></i><b>6.2</b> Automatisch</a></li>
<li class="chapter" data-level="6.3" data-path="daten-erstellen.html"><a href="daten-erstellen.html#zufällig"><i class="fa fa-check"></i><b>6.3</b> Zufällig</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html"><i class="fa fa-check"></i><b>7</b> Daten importieren und speichern</a>
<ul>
<li class="chapter" data-level="7.1" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#funktionen-zur-organisation-des-workspace"><i class="fa fa-check"></i><b>7.1</b> Funktionen zur Organisation des Workspace</a></li>
<li class="chapter" data-level="7.2" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#arbeitsverzeichnis-working-directory"><i class="fa fa-check"></i><b>7.2</b> Arbeitsverzeichnis (Working Directory)</a></li>
<li class="chapter" data-level="7.3" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#working-environment"><i class="fa fa-check"></i><b>7.3</b> Working Environment</a></li>
<li class="chapter" data-level="7.4" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#daten-importieren"><i class="fa fa-check"></i><b>7.4</b> Daten importieren</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#rds-format"><i class="fa fa-check"></i><b>7.4.1</b> rds-Format</a></li>
<li class="chapter" data-level="7.4.2" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#csv-format"><i class="fa fa-check"></i><b>7.4.2</b> csv-Format</a></li>
<li class="chapter" data-level="7.4.3" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#sav-format"><i class="fa fa-check"></i><b>7.4.3</b> sav-Format</a></li>
<li class="chapter" data-level="7.4.4" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#xlsx-format"><i class="fa fa-check"></i><b>7.4.4</b> xlsx-Format</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#daten-speichern"><i class="fa fa-check"></i><b>7.5</b> Daten speichern</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#rds-format-1"><i class="fa fa-check"></i><b>7.5.1</b> rds-Format</a></li>
<li class="chapter" data-level="7.5.2" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#csv-format-1"><i class="fa fa-check"></i><b>7.5.2</b> csv-Format</a></li>
<li class="chapter" data-level="7.5.3" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#sav-format-1"><i class="fa fa-check"></i><b>7.5.3</b> sav-Format</a></li>
<li class="chapter" data-level="7.5.4" data-path="daten-importieren-und-speichern.html"><a href="daten-importieren-und-speichern.html#xlsx-format-1"><i class="fa fa-check"></i><b>7.5.4</b> xlsx-Format</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="daten-auswählen.html"><a href="daten-auswählen.html"><i class="fa fa-check"></i><b>8</b> Daten auswählen</a>
<ul>
<li class="chapter" data-level="8.1" data-path="daten-auswählen.html"><a href="daten-auswählen.html#vektor-1"><i class="fa fa-check"></i><b>8.1</b> Vektor</a></li>
<li class="chapter" data-level="8.2" data-path="daten-auswählen.html"><a href="daten-auswählen.html#dataframe"><i class="fa fa-check"></i><b>8.2</b> Dataframe</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="daten-auswählen.html"><a href="daten-auswählen.html#zeilen-fälle-auswählen"><i class="fa fa-check"></i><b>8.2.1</b> Zeilen (Fälle) auswählen</a></li>
<li class="chapter" data-level="8.2.2" data-path="daten-auswählen.html"><a href="daten-auswählen.html#spalten-variablen-auswählen"><i class="fa fa-check"></i><b>8.2.2</b> Spalten (Variablen) auswählen</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="daten-explorieren.html"><a href="daten-explorieren.html"><i class="fa fa-check"></i><b>9</b> Daten Explorieren</a>
<ul>
<li class="chapter" data-level="9.1" data-path="daten-explorieren.html"><a href="daten-explorieren.html#informationen-über-r-objekte"><i class="fa fa-check"></i><b>9.1</b> Informationen über R Objekte</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="daten-explorieren.html"><a href="daten-explorieren.html#informationen-über-vektoren"><i class="fa fa-check"></i><b>9.1.1</b> Informationen über Vektoren</a></li>
<li class="chapter" data-level="9.1.2" data-path="daten-explorieren.html"><a href="daten-explorieren.html#informationen-über-dataframes"><i class="fa fa-check"></i><b>9.1.2</b> Informationen über Dataframes</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="daten-explorieren.html"><a href="daten-explorieren.html#deskriptivstatistiken"><i class="fa fa-check"></i><b>9.2</b> Deskriptivstatistiken</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="daten-explorieren.html"><a href="daten-explorieren.html#kategorische-variablen"><i class="fa fa-check"></i><b>9.2.1</b> Kategorische Variablen</a></li>
<li class="chapter" data-level="9.2.2" data-path="daten-explorieren.html"><a href="daten-explorieren.html#numerische-variablen"><i class="fa fa-check"></i><b>9.2.2</b> Numerische Variablen</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="datenmanipulation.html"><a href="datenmanipulation.html"><i class="fa fa-check"></i><b>10</b> Datenmanipulation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="datenmanipulation.html"><a href="datenmanipulation.html#daten-hinzufügen"><i class="fa fa-check"></i><b>10.1</b> Daten hinzufügen</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="datenmanipulation.html"><a href="datenmanipulation.html#variablen-hinzufügen"><i class="fa fa-check"></i><b>10.1.1</b> Variablen hinzufügen</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="datenmanipulation.html"><a href="datenmanipulation.html#daten-löschen"><i class="fa fa-check"></i><b>10.2</b> Daten löschen</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="datenmanipulation.html"><a href="datenmanipulation.html#variablen-löschen"><i class="fa fa-check"></i><b>10.2.1</b> Variablen löschen</a></li>
<li class="chapter" data-level="10.2.2" data-path="datenmanipulation.html"><a href="datenmanipulation.html#fälle-löschen"><i class="fa fa-check"></i><b>10.2.2</b> Fälle löschen</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="datenmanipulation.html"><a href="datenmanipulation.html#variablen-umbenennen"><i class="fa fa-check"></i><b>10.3</b> Variablen umbenennen</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="datenmanipulation.html"><a href="datenmanipulation.html#variablennamen-ändern"><i class="fa fa-check"></i><b>10.3.1</b> Variablennamen ändern</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="datenmanipulation.html"><a href="datenmanipulation.html#daten-verändern"><i class="fa fa-check"></i><b>10.4</b> Daten verändern</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="datenmanipulation.html"><a href="datenmanipulation.html#werte-ändern"><i class="fa fa-check"></i><b>10.4.1</b> Werte ändern</a></li>
<li class="chapter" data-level="10.4.2" data-path="datenmanipulation.html"><a href="datenmanipulation.html#recodieren"><i class="fa fa-check"></i><b>10.4.2</b> Recodieren</a></li>
<li class="chapter" data-level="10.4.3" data-path="datenmanipulation.html"><a href="datenmanipulation.html#worte-ändern"><i class="fa fa-check"></i><b>10.4.3</b> Worte ändern</a></li>
<li class="chapter" data-level="10.4.4" data-path="datenmanipulation.html"><a href="datenmanipulation.html#faktorstufen-ändern"><i class="fa fa-check"></i><b>10.4.4</b> Faktorstufen ändern</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="datenmanipulation.html"><a href="datenmanipulation.html#daten-sortieren"><i class="fa fa-check"></i><b>10.5</b> Daten sortieren</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="datenmanipulation.html"><a href="datenmanipulation.html#sortieren-nach-numerischen-variablen"><i class="fa fa-check"></i><b>10.5.1</b> Sortieren nach numerischen Variablen</a></li>
<li class="chapter" data-level="10.5.2" data-path="datenmanipulation.html"><a href="datenmanipulation.html#sortieren-nach-variablen-mit-worten"><i class="fa fa-check"></i><b>10.5.2</b> Sortieren nach Variablen mit Worten</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="datenmanipulation.html"><a href="datenmanipulation.html#datensätze-zusammensetzen"><i class="fa fa-check"></i><b>10.6</b> Datensätze zusammensetzen</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="datenmanipulation.html"><a href="datenmanipulation.html#cbind-und-rbind"><i class="fa fa-check"></i><b>10.6.1</b> cbind und rbind</a></li>
<li class="chapter" data-level="10.6.2" data-path="datenmanipulation.html"><a href="datenmanipulation.html#merge"><i class="fa fa-check"></i><b>10.6.2</b> merge</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="schleifen-loops.html"><a href="schleifen-loops.html"><i class="fa fa-check"></i><b>11</b> Schleifen (Loops)</a>
<ul>
<li class="chapter" data-level="11.1" data-path="schleifen-loops.html"><a href="schleifen-loops.html#for"><i class="fa fa-check"></i><b>11.1</b> for()</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="graphiken.html"><a href="graphiken.html"><i class="fa fa-check"></i><b>12</b> Graphiken</a>
<ul>
<li class="chapter" data-level="12.1" data-path="graphiken.html"><a href="graphiken.html#das-ggplot2-paket"><i class="fa fa-check"></i><b>12.1</b> Das ggplot2 Paket</a></li>
<li class="chapter" data-level="12.2" data-path="graphiken.html"><a href="graphiken.html#ggplot"><i class="fa fa-check"></i><b>12.2</b> ggplot()</a></li>
<li class="chapter" data-level="12.3" data-path="graphiken.html"><a href="graphiken.html#streu-punktdiagramm"><i class="fa fa-check"></i><b>12.3</b> Streu-/Punktdiagramm</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="graphiken.html"><a href="graphiken.html#streudiagramm-mit-2-variablen"><i class="fa fa-check"></i><b>12.3.1</b> Streudiagramm mit 2 Variablen</a></li>
<li class="chapter" data-level="12.3.2" data-path="graphiken.html"><a href="graphiken.html#geom_point"><i class="fa fa-check"></i><b>12.3.2</b> geom_point()</a></li>
<li class="chapter" data-level="12.3.3" data-path="graphiken.html"><a href="graphiken.html#geom_smooth"><i class="fa fa-check"></i><b>12.3.3</b> geom_smooth()</a></li>
<li class="chapter" data-level="12.3.4" data-path="graphiken.html"><a href="graphiken.html#streudiagramm-mit-mehr-als-2-variablen"><i class="fa fa-check"></i><b>12.3.4</b> Streudiagramm mit mehr als 2 Variablen</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="graphiken.html"><a href="graphiken.html#histogramm"><i class="fa fa-check"></i><b>12.4</b> Histogramm</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="graphiken.html"><a href="graphiken.html#histogramm-für-mehrere-gruppen"><i class="fa fa-check"></i><b>12.4.1</b> Histogramm für mehrere Gruppen</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="graphiken.html"><a href="graphiken.html#balkendiagramm"><i class="fa fa-check"></i><b>12.5</b> Balkendiagramm</a></li>
<li class="chapter" data-level="12.6" data-path="graphiken.html"><a href="graphiken.html#balkendiagramm-mit-mehr-als-3-variablen"><i class="fa fa-check"></i><b>12.6</b> Balkendiagramm mit mehr als 3 Variablen</a></li>
<li class="chapter" data-level="12.7" data-path="graphiken.html"><a href="graphiken.html#boxplot"><i class="fa fa-check"></i><b>12.7</b> Boxplot</a></li>
<li class="chapter" data-level="12.8" data-path="graphiken.html"><a href="graphiken.html#facetting"><i class="fa fa-check"></i><b>12.8</b> Facetting</a></li>
<li class="chapter" data-level="12.9" data-path="graphiken.html"><a href="graphiken.html#ästhetische-anpassungen"><i class="fa fa-check"></i><b>12.9</b> Ästhetische Anpassungen</a>
<ul>
<li class="chapter" data-level="12.9.1" data-path="graphiken.html"><a href="graphiken.html#ggtitle"><i class="fa fa-check"></i><b>12.9.1</b> ggtitle()</a></li>
<li class="chapter" data-level="12.9.2" data-path="graphiken.html"><a href="graphiken.html#labs"><i class="fa fa-check"></i><b>12.9.2</b> labs()</a></li>
<li class="chapter" data-level="12.9.3" data-path="graphiken.html"><a href="graphiken.html#achsen-verändern"><i class="fa fa-check"></i><b>12.9.3</b> Achsen verändern</a></li>
</ul></li>
<li class="chapter" data-level="12.10" data-path="graphiken.html"><a href="graphiken.html#theme"><i class="fa fa-check"></i><b>12.10</b> theme()</a>
<ul>
<li class="chapter" data-level="12.10.1" data-path="graphiken.html"><a href="graphiken.html#elemente-von-theme"><i class="fa fa-check"></i><b>12.10.1</b> Elemente von theme()</a></li>
<li class="chapter" data-level="12.10.2" data-path="graphiken.html"><a href="graphiken.html#legende"><i class="fa fa-check"></i><b>12.10.2</b> Legende</a></li>
<li class="chapter" data-level="12.10.3" data-path="graphiken.html"><a href="graphiken.html#vorgefertigte-themes"><i class="fa fa-check"></i><b>12.10.3</b> Vorgefertigte themes</a></li>
</ul></li>
<li class="chapter" data-level="12.11" data-path="graphiken.html"><a href="graphiken.html#abbildungen-kombinieren"><i class="fa fa-check"></i><b>12.11</b> Abbildungen kombinieren</a></li>
<li class="chapter" data-level="12.12" data-path="graphiken.html"><a href="graphiken.html#abbildungen-exportieren"><i class="fa fa-check"></i><b>12.12</b> Abbildungen exportieren</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="korrelation.html"><a href="korrelation.html"><i class="fa fa-check"></i><b>13</b> Korrelation</a>
<ul>
<li class="chapter" data-level="13.1" data-path="korrelation.html"><a href="korrelation.html#hypothesen"><i class="fa fa-check"></i><b>13.1</b> Hypothesen</a></li>
<li class="chapter" data-level="13.2" data-path="korrelation.html"><a href="korrelation.html#berechnung-der-korrelation"><i class="fa fa-check"></i><b>13.2</b> Berechnung der Korrelation</a></li>
<li class="chapter" data-level="13.3" data-path="korrelation.html"><a href="korrelation.html#unterschiedliche-korrelationsmethoden"><i class="fa fa-check"></i><b>13.3</b> Unterschiedliche Korrelationsmethoden</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="korrelation.html"><a href="korrelation.html#pearson-korrelation"><i class="fa fa-check"></i><b>13.3.1</b> Pearson-Korrelation</a></li>
<li class="chapter" data-level="13.3.2" data-path="korrelation.html"><a href="korrelation.html#spearman-korrelation-aka-rangkorrelation"><i class="fa fa-check"></i><b>13.3.2</b> Spearman-Korrelation (aka Rangkorrelation)</a></li>
<li class="chapter" data-level="13.3.3" data-path="korrelation.html"><a href="korrelation.html#kendall-korrelation"><i class="fa fa-check"></i><b>13.3.3</b> Kendall-Korrelation</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="korrelation.html"><a href="korrelation.html#korrelation-als-hypothesentest"><i class="fa fa-check"></i><b>13.4</b> Korrelation als Hypothesentest</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html"><i class="fa fa-check"></i><b>14</b> Einfache Hypothesentests</a>
<ul>
<li class="chapter" data-level="14.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#ein-stichproben-t-test"><i class="fa fa-check"></i><b>14.1</b> Ein-Stichproben t-Test</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#hypothesen-1"><i class="fa fa-check"></i><b>14.1.1</b> Hypothesen</a></li>
<li class="chapter" data-level="14.1.2" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#deskriptive-einordnung"><i class="fa fa-check"></i><b>14.1.2</b> Deskriptive Einordnung</a></li>
<li class="chapter" data-level="14.1.3" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#test-durchführen"><i class="fa fa-check"></i><b>14.1.3</b> Test durchführen</a></li>
<li class="chapter" data-level="14.1.4" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#ergebnis-interpretieren"><i class="fa fa-check"></i><b>14.1.4</b> Ergebnis interpretieren</a></li>
<li class="chapter" data-level="14.1.5" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#ergebnis-berichten"><i class="fa fa-check"></i><b>14.1.5</b> Ergebnis berichten</a></li>
<li class="chapter" data-level="14.1.6" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#effektstärke"><i class="fa fa-check"></i><b>14.1.6</b> Effektstärke</a></li>
<li class="chapter" data-level="14.1.7" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#darstellung-in-tabellenform"><i class="fa fa-check"></i><b>14.1.7</b> Darstellung in Tabellenform</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#t-test-bei-unabhängigen-stichproben"><i class="fa fa-check"></i><b>14.2</b> t-Test bei unabhängigen Stichproben</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#hypothesen-2"><i class="fa fa-check"></i><b>14.2.1</b> Hypothesen</a></li>
<li class="chapter" data-level="14.2.2" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#deskriptive-einordnung-1"><i class="fa fa-check"></i><b>14.2.2</b> Deskriptive Einordnung</a></li>
<li class="chapter" data-level="14.2.3" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#test-durchführen-1"><i class="fa fa-check"></i><b>14.2.3</b> Test durchführen</a></li>
<li class="chapter" data-level="14.2.4" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#relevante-parameter-extrahieren"><i class="fa fa-check"></i><b>14.2.4</b> Relevante Parameter extrahieren</a></li>
<li class="chapter" data-level="14.2.5" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#voraussetzungsprüfung-und-alternativen"><i class="fa fa-check"></i><b>14.2.5</b> Voraussetzungsprüfung und Alternativen</a></li>
<li class="chapter" data-level="14.2.6" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#effektstärke-1"><i class="fa fa-check"></i><b>14.2.6</b> Effektstärke</a></li>
<li class="chapter" data-level="14.2.7" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#darstellung-in-tabellenform-1"><i class="fa fa-check"></i><b>14.2.7</b> Darstellung in Tabellenform</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#t-test-bei-abhängigen-stichproben"><i class="fa fa-check"></i><b>14.3</b> t-Test bei abhängigen Stichproben</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#hypothesen-3"><i class="fa fa-check"></i><b>14.3.1</b> Hypothesen</a></li>
<li class="chapter" data-level="14.3.2" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#deskriptive-einordnung-2"><i class="fa fa-check"></i><b>14.3.2</b> Deskriptive Einordnung</a></li>
<li class="chapter" data-level="14.3.3" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#test-durchführen-2"><i class="fa fa-check"></i><b>14.3.3</b> Test durchführen</a></li>
<li class="chapter" data-level="14.3.4" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#relevante-parameter-extrahieren-1"><i class="fa fa-check"></i><b>14.3.4</b> Relevante Parameter extrahieren</a></li>
<li class="chapter" data-level="14.3.5" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#voraussetzungsprüfung-und-alternativen-1"><i class="fa fa-check"></i><b>14.3.5</b> Voraussetzungsprüfung und Alternativen</a></li>
<li class="chapter" data-level="14.3.6" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#effektstärke-2"><i class="fa fa-check"></i><b>14.3.6</b> Effektstärke</a></li>
<li class="chapter" data-level="14.3.7" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#darstellung-in-tabellenform-2"><i class="fa fa-check"></i><b>14.3.7</b> Darstellung in Tabellenform</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#wilcoxonmannwhitney-u-test-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>14.4</b> Wilcoxon–Mann–Whitney-U Test (Wilcoxon rank sum test)</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#hypothesen-4"><i class="fa fa-check"></i><b>14.4.1</b> Hypothesen</a></li>
<li class="chapter" data-level="14.4.2" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#test-durchführen-3"><i class="fa fa-check"></i><b>14.4.2</b> Test durchführen</a></li>
<li class="chapter" data-level="14.4.3" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#relevante-parameter-extrahieren-2"><i class="fa fa-check"></i><b>14.4.3</b> Relevante Parameter extrahieren</a></li>
<li class="chapter" data-level="14.4.4" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#effektstärke-3"><i class="fa fa-check"></i><b>14.4.4</b> Effektstärke</a></li>
<li class="chapter" data-level="14.4.5" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#darstellung-in-tabellenform-3"><i class="fa fa-check"></i><b>14.4.5</b> Darstellung in Tabellenform</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#wilcoxonmannu-test-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>14.5</b> Wilcoxon–Mann–U Test (Wilcoxon signed rank test)</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#hypothesen-5"><i class="fa fa-check"></i><b>14.5.1</b> Hypothesen</a></li>
<li class="chapter" data-level="14.5.2" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#test-durchführen-4"><i class="fa fa-check"></i><b>14.5.2</b> Test durchführen</a></li>
<li class="chapter" data-level="14.5.3" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#relevante-parameter-extrahieren-3"><i class="fa fa-check"></i><b>14.5.3</b> Relevante Parameter extrahieren</a></li>
<li class="chapter" data-level="14.5.4" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#effektstärke-4"><i class="fa fa-check"></i><b>14.5.4</b> Effektstärke</a></li>
<li class="chapter" data-level="14.5.5" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#darstellung-in-tabellenform-4"><i class="fa fa-check"></i><b>14.5.5</b> Darstellung in Tabellenform</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#chi2-test"><i class="fa fa-check"></i><b>14.6</b> <span class="math inline">\(\chi\)</span><sup>2</sup>-Test</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#deskriptive-einordnung-3"><i class="fa fa-check"></i><b>14.6.1</b> Deskriptive Einordnung</a></li>
<li class="chapter" data-level="14.6.2" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#test-durchführen-5"><i class="fa fa-check"></i><b>14.6.2</b> Test durchführen</a></li>
<li class="chapter" data-level="14.6.3" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#relevante-parameter-extrahieren-4"><i class="fa fa-check"></i><b>14.6.3</b> Relevante Parameter extrahieren</a></li>
<li class="chapter" data-level="14.6.4" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#voraussetzungsprüfung-und-alternativen-2"><i class="fa fa-check"></i><b>14.6.4</b> Voraussetzungsprüfung und Alternativen</a></li>
<li class="chapter" data-level="14.6.5" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#effektstärke-5"><i class="fa fa-check"></i><b>14.6.5</b> Effektstärke</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#fishers-exakter-test"><i class="fa fa-check"></i><b>14.7</b> Fisher’s Exakter Test</a>
<ul>
<li class="chapter" data-level="14.7.1" data-path="einfache-hypothesentests.html"><a href="einfache-hypothesentests.html#test-durchführen-6"><i class="fa fa-check"></i><b>14.7.1</b> Test durchführen</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>15</b> ANOVA</a>
<ul>
<li class="chapter" data-level="15.1" data-path="anova.html"><a href="anova.html#einfaktorielle-anova"><i class="fa fa-check"></i><b>15.1</b> Einfaktorielle ANOVA</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="anova.html"><a href="anova.html#alpha-fehler-kumulierung"><i class="fa fa-check"></i><b>15.1.1</b> <span class="math inline">\(\alpha\)</span>-Fehler Kumulierung</a></li>
<li class="chapter" data-level="15.1.2" data-path="anova.html"><a href="anova.html#deskriptive-einordnung-4"><i class="fa fa-check"></i><b>15.1.2</b> Deskriptive Einordnung</a></li>
<li class="chapter" data-level="15.1.3" data-path="anova.html"><a href="anova.html#berechnung-der-anova"><i class="fa fa-check"></i><b>15.1.3</b> Berechnung der ANOVA</a></li>
<li class="chapter" data-level="15.1.4" data-path="anova.html"><a href="anova.html#interpretation"><i class="fa fa-check"></i><b>15.1.4</b> Interpretation</a></li>
<li class="chapter" data-level="15.1.5" data-path="anova.html"><a href="anova.html#post-hoc-tests"><i class="fa fa-check"></i><b>15.1.5</b> Post-hoc Tests</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="anova.html"><a href="anova.html#mehrfaktorielle-anova"><i class="fa fa-check"></i><b>15.2</b> Mehrfaktorielle ANOVA</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="anova.html"><a href="anova.html#deskriptive-einordnung-5"><i class="fa fa-check"></i><b>15.2.1</b> Deskriptive Einordnung</a></li>
<li class="chapter" data-level="15.2.2" data-path="anova.html"><a href="anova.html#berechnung-der-anova-1"><i class="fa fa-check"></i><b>15.2.2</b> Berechnung der ANOVA</a></li>
<li class="chapter" data-level="15.2.3" data-path="anova.html"><a href="anova.html#interpretation-1"><i class="fa fa-check"></i><b>15.2.3</b> Interpretation</a></li>
<li class="chapter" data-level="15.2.4" data-path="anova.html"><a href="anova.html#post-hoc-tests-1"><i class="fa fa-check"></i><b>15.2.4</b> Post-hoc Tests</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="anova.html"><a href="anova.html#prüfen-der-voraussetzungen-von-anovas"><i class="fa fa-check"></i><b>15.3</b> Prüfen der Voraussetzungen von ANOVAs</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="anova.html"><a href="anova.html#testen-der-empirisch-testbaren-annahmen"><i class="fa fa-check"></i><b>15.3.1</b> Testen der empirisch testbaren Annahmen</a></li>
<li class="chapter" data-level="15.3.2" data-path="anova.html"><a href="anova.html#homogenität-der-varianzen"><i class="fa fa-check"></i><b>15.3.2</b> Homogenität der Varianzen:</a></li>
<li class="chapter" data-level="15.3.3" data-path="anova.html"><a href="anova.html#sphärizität"><i class="fa fa-check"></i><b>15.3.3</b> Sphärizität:</a></li>
<li class="chapter" data-level="15.3.4" data-path="anova.html"><a href="anova.html#normalverteilung-der-residuen"><i class="fa fa-check"></i><b>15.3.4</b> Normalverteilung der Residuen:</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Einführung in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova" class="section level1 hasAnchor" number="15">
<h1><span class="header-section-number">Kapitel 15</span> ANOVA<a href="anova.html#anova" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Die ANOVA (Analysis of variance, dt. Varianzanalyse) ist ein weiterer Signifikanztest. Mit der ANOVA können wir Prüfen, ob eine unabhängige Variable (UV) einen signifikanten Anteil Varianz der abhängigen Variable erklärt (AV). Die UVs nennen wir bei der ANOVA i.d.R. <strong>Faktor</strong>.</p>
<p>Statistisch ist die ANOVA ein F-Test (Varianzquotient).</p>
<div id="einfaktorielle-anova" class="section level2 hasAnchor" number="15.1">
<h2><span class="header-section-number">15.1</span> Einfaktorielle ANOVA<a href="anova.html#einfaktorielle-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Wir nutzen die ANOVA besonders gerne, wenn wir eine numerische AV und einen kategorialen Faktor mit <span class="math inline">\(&gt;2\)</span> Stufen haben.</p>
<p>Ein Beispiel wäre der Vergleich der Stärke von Symptomen, die Patient:innen nach einer Therapie haben. Klinisch wäre es wünschenswert, dass die Symptomstärke nach der Therapie möglichst gering ausfällt.</p>
<p>Laden wir uns einen fiktiven Datensatz herunter, der dieses Szenario wiederspiegelt:</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="anova.html#cb425-1" aria-hidden="true" tabindex="-1"></a>therapy <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/stephangoerigk/WAF_Folien/master/therapy4groups.csv&quot;</span>)[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb425-2"><a href="anova.html#cb425-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb425-3"><a href="anova.html#cb425-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(therapy)</span></code></pre></div>
<pre><code>##        X            Therapy     Symptoms         Diagnosis 
##  Min.   : 1.00   Control:8   Min.   :15.0   Angst     :15  
##  1st Qu.: 8.25   PA     :8   1st Qu.:48.5   Depression:15  
##  Median :15.50   SSRI   :8   Median :61.0                  
##  Mean   :15.50   VT     :6   Mean   :60.0                  
##  3rd Qu.:22.75               3rd Qu.:70.0                  
##  Max.   :30.00               Max.   :90.0</code></pre>
<p>In diesem Datensatz repräsentiert jede Zeile eine Patient:in mit einer Depression bzw. Angststörung, die mit einer von 4 Therapien behandelt wurde:</p>
<ul>
<li>SSRI = ein Antidepressivum (Selektive Serotoninwiederaufnahmehemmer)</li>
<li>VT = Verhaltenstherapie</li>
<li>PA = Psychoanalyse</li>
<li>Control = Kontrollbedingung (keine Therapie)</li>
</ul>
<p>Die Therapie (UV) ist also ein Faktor mit 4 Stufen.</p>
<p>Eine denkbare Forschungsfrage könnte wie folgt lauten:</p>
<p><em>Nach welcher Therapie haben die Patient:innen die schwächsten Symptome?</em></p>
<div id="alpha-fehler-kumulierung" class="section level3 hasAnchor" number="15.1.1">
<h3><span class="header-section-number">15.1.1</span> <span class="math inline">\(\alpha\)</span>-Fehler Kumulierung<a href="anova.html#alpha-fehler-kumulierung" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In unserem Beispiel mit 4 Gruppen könnten wir den t-Test nicht verwenden, da dieser max. 2 Mittelwerte vergleicht. Intuitiv könnte man sich überlegen, statt eines t-Tests einfach insgesamt 6 t-Tests zu rechnen, um alle Vergleiche abzudecken (SSRI vs. VT, VT vs. PA, …). Was uns daran hindert, ist die sogenannte <span class="math inline">\(\alpha\)</span>-Fehler Kumulierung.</p>
<p>Unter Annahme eines Signifikanzniveaus von <span class="math inline">\(\alpha=.05\)</span> erlauben wir uns 5% Wahrscheinlichkeit einen Fehler 1. Art zu begehen (fälschlicherweise die <span class="math inline">\(H_1\)</span> anzunehmen). Diese 5% Fehlerwahrscheinlichkeit besteht jedoch bei jedem einzelnen t-Test <span class="math inline">\(\rightarrow\)</span> Viele Tests, viele mögliche Fehlerentscheidungen!</p>
<p>Selbst bei 3 t-Tests steigt die Wahrscheinlichkeit für einen Fehler 1. Art mit <span class="math inline">\(0.05^3=0.14\)</span> rasant auf 14% statt 5% an.</p>
<p>Um dieses Problem zu vermeiden rechenen wir die ANOVA, welche uns nicht alle Vergleiche einzeln, sondern die Signifikanz des gesamten Faktors auf einmal berechnet (Omnibus Test). Daraus folgt jedoch auch, dass die ANOVA als Signifikanztest Hypothesen <strong>immer ungerichtet</strong> testet.</p>
</div>
<div id="deskriptive-einordnung-4" class="section level3 hasAnchor" number="15.1.2">
<h3><span class="header-section-number">15.1.2</span> Deskriptive Einordnung<a href="anova.html#deskriptive-einordnung-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Zunächst können wir uns die Deskriptivstatistiken innerhalb der 4 Gruppen einmal anschauen:</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="anova.html#cb427-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describeBy</span>(Symptoms <span class="sc">~</span> Therapy, <span class="at">data =</span> therapy)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## Therapy: Control
##          vars n  mean   sd median trimmed mad min max range  skew kurtosis   se
## Symptoms    1 8 73.75 8.15   72.5   73.75 8.9  59  82    23 -0.39    -1.25 2.88
## ------------------------------------------------------------ 
## Therapy: PA
##          vars n  mean    sd median trimmed   mad min max range skew kurtosis
## Symptoms    1 8 64.62 13.38     62   64.62 11.12  47  90    43 0.54    -0.93
##            se
## Symptoms 4.73
## ------------------------------------------------------------ 
## Therapy: SSRI
##          vars n  mean   sd median trimmed  mad min max range skew kurtosis  se
## Symptoms    1 8 56.88 13.3     54   56.88 12.6  39  80    41 0.36    -1.29 4.7
## ------------------------------------------------------------ 
## Therapy: VT
##          vars n  mean    sd median trimmed  mad min max range skew kurtosis
## Symptoms    1 6 39.67 17.85     38   39.67 12.6  15  68    53 0.22    -1.32
##            se
## Symptoms 7.29</code></pre>
<p>Rein deskriptiv lässt sich bereits feststellen, dass Patient:innen nach der VT die niedrigsten Symptome aufweisen (M [SD]=39.67 [17.85]), gefolgt von SSRI (M [SD]=56.88 [13.3]), PA (M [SD]=64.62 [13.38]) und Control (M [SD]=73.75 [8.15]).</p>
<p>Die Gruppenunterschiede lassen sich auch graphisch gut darstellen:</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="anova.html#cb429-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> therapy, <span class="fu">aes</span>(<span class="at">x =</span> Therapy, <span class="at">y =</span> Symptoms)) <span class="sc">+</span></span>
<span id="cb429-2"><a href="anova.html#cb429-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se,  <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>) <span class="sc">+</span></span>
<span id="cb429-3"><a href="anova.html#cb429-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">fun =</span> mean) </span></code></pre></div>
<p><img src="CFH_R_bookdown_files/figure-html/unnamed-chunk-261-1.png" width="672" /></p>
<p>Ob sich die numerischen Unterschiede sich auch als signifikant erweisen, prüfen wir mit der ANOVA.</p>
</div>
<div id="berechnung-der-anova" class="section level3 hasAnchor" number="15.1.3">
<h3><span class="header-section-number">15.1.3</span> Berechnung der ANOVA<a href="anova.html#berechnung-der-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Die einfaktorielle ANOVA lässt sich in R auf zwei Arten berechnen, die beide zu dem exakt selben Ergebnis kommen.</p>
<ul>
<li>eingebaute <code>lm()</code> Funktion gefolgt von <code>anova()</code></li>
<li><code>aov_ez()</code> Funktion aus dem <code>afex</code> Paket</li>
</ul>
<div id="berechnung-mittels-lm" class="section level4 hasAnchor" number="15.1.3.1">
<h4><span class="header-section-number">15.1.3.1</span> Berechnung mittels <code>lm()</code><a href="anova.html#berechnung-mittels-lm" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Die <code>lm()</code> Funktion ist eine der gebräuchlichsten in der Statistik überhaupt. Sie ist nach dem <strong>Allgemeinen linearen Modell</strong> benannt (<strong>l</strong>inear <strong>m</strong>odel) und wird beispielsweise auch zur Berechnung der Regression verwendet.</p>
<p>Das lineare Modell wird wie folgt aufgestellt (Formelformat):</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="anova.html#cb430-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">=</span> <span class="fu">lm</span>(Symptoms <span class="sc">~</span> Therapy, <span class="at">data =</span> therapy)</span></code></pre></div>
<p>In der Formel steht links immer die AV (Symptoms). Die <code>~</code> Symbol heißt soviel wie “wird vorhergesagt durch”. Auf der rechten Seite steht die UV (Therapy).</p>
<p>Um das Ergebnis der ANOVA (den F-Test) zu erhalten, müssen wir die Funktion <code>anova()</code> auf das erstellte Modell anwenden</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="anova.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Symptoms
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Therapy    3 4242.4 1414.14   8.078 0.0005766 ***
## Residuals 26 4551.6  175.06                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Wir erhalten den Output der ANOVA mit allen relevanten Zahlen:</p>
<ul>
<li>Df = Freiheitsgrade (VORSICHT der F-Test hat 2x df <span class="math inline">\(\rightarrow\)</span> Zähler-/ und Nennerfreiheitsgrade)</li>
<li>F-Wert = Teststatistik (könnte in F-Tabelle nachgesehen werden)</li>
<li>p-Wert <span class="math inline">\(\rightarrow\)</span> entscheidend dafür, ob ANOVA signifikant ist</li>
</ul>
<p>Die Entscheidungsregel ist uns bereits bekannt: Ist der p-Wert (hier <span class="math inline">\(p=0.0005766\)</span>) kleiner als <span class="math inline">\(\alpha=.05\)</span> ist der Test signifikant. Das ist hier der Fall. Das ganze Ergebnis schreibt man i.d.R. wie folgt: <span class="math inline">\(F_{3,26}=8.08, p&lt;.001\)</span>.</p>
</div>
<div id="berechnung-mittels-aov_ez" class="section level4 hasAnchor" number="15.1.3.2">
<h4><span class="header-section-number">15.1.3.2</span> Berechnung mittels <code>aov_ez()</code><a href="anova.html#berechnung-mittels-aov_ez" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Die Berechnung mit der <code>aov_ez()</code> Funktion erfolgt analog, nur wird die Formel etwas anders geschrieben.</p>
<p>Wir legen genau fest, was unsere AV ist <code>dv</code>. Zudem brauchen wir eine Variable, die jede Zeile eindeutig einem Individuum zuordnet <code>id</code>.</p>
<p>Die Faktoren (UVs) werden mit einem der beiden folgenden Argumente angegeben:</p>
<ul>
<li><code>between</code> (Zwischensubjektfaktoren)</li>
<li><code>within</code> (Innersubjektfaktoren)</li>
</ul>
<p>Faktoren, die unter <code>between</code> angegeben werden, sind unabhängige Messungen, also Variablen die einen Gruppenvergleich möglich machen. Faktoren, die unter <code>within</code> angegeben werden, sind abhängige Messungen, also beispielsweise mehrere Messzeitpunkte derselben Person.</p>
<p>In unserem Fall liegt ein Gruppenvergleich vor (jede Person hat jeweils nur eine der Therapien erhalten), daher nutzen wir <code>between</code>. Für <code>id</code> nutzen wir einfach die Variable <code>X</code>, die einen Patientencode für jede Person enthält.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="anova.html#cb433-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span>
<span id="cb433-2"><a href="anova.html#cb433-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">=</span> <span class="fu">aov_ez</span>(<span class="at">dv =</span> <span class="st">&quot;Symptoms&quot;</span>, <span class="at">between =</span> <span class="fu">c</span>(<span class="st">&quot;Therapy&quot;</span>), <span class="at">id =</span> <span class="st">&quot;X&quot;</span>, <span class="at">data =</span> therapy)</span>
<span id="cb433-3"><a href="anova.html#cb433-3" aria-hidden="true" tabindex="-1"></a>mod</span></code></pre></div>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: Symptoms
##    Effect    df    MSE        F  ges p.value
## 1 Therapy 3, 26 175.06 8.08 *** .482   &lt;.001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Wie wir sehen, wird der Schritt des Aufstellens des linearen Modells hier übersprungen und direkt die ANOVA (F-Test) gerechnet.
Das Ergebnise ist jedoch identisch.</p>
</div>
</div>
<div id="interpretation" class="section level3 hasAnchor" number="15.1.4">
<h3><span class="header-section-number">15.1.4</span> Interpretation<a href="anova.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Die ANOVA ist in unserem Beispiel signifikant geworden. Dies gibt uns die Information, dass der Faktor Therapie einen signifikanten Anteil der Varianz unserer AV (Symptoms) erklären kann. Anders gesagt: Es scheinen hinsichtlich der Symptomatik Unterschiede zwischen den Gruppen zu bestehen.</p>
<p>Aus dem signifikanten Ergebnis der ANOVA können wir jedoch nicht erkennen, <strong>zwischen welchen der Gruppen</strong> die Unterschiede genau bestehen. Wir wissen es gibt einen Effekt, nur nicht wo er liegt.</p>
<p>Aus diesem Grund folgt auf die Berechnung der ANOVA ein zweiter Schritt, um mittels <strong>paarweisen Vergleichen</strong> zu prüfen, wo die Unterschiede liegen. Diese paarweisen Vergleiche nennt man auch Post-hoc Tests</p>
</div>
<div id="post-hoc-tests" class="section level3 hasAnchor" number="15.1.5">
<h3><span class="header-section-number">15.1.5</span> Post-hoc Tests<a href="anova.html#post-hoc-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Post-hoc Tests erlauben uns genau zu sehen, welche der Stufen unserer UV sich unterscheiden. In diesem Sinne sind sie nichts anderes als nachgeschaltete t-Tests, die 2 Gruppen miteinander vergleichen.</p>
<p>Wir berechnen Post-hoc Tests mit der <code>emmeans()</code> Funktion aus dem gleichnamigen <code>emmeans</code> Paket. Die Abkürzung emmeans bedeuted “estimated marginal means”, was soviel bedeutet wie die Mittelwerte des Modells innerhalb der Faktorstufen zu vergleichen.</p>
<p>Die <code>emmeans()</code> Funktion kann man sowohl nach der ANOVA mit <code>lm()</code> als auch nach der ANOVA mit <code>aov_ez()</code> verwenden.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="anova.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb435-2"><a href="anova.html#cb435-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod, pairwise <span class="sc">~</span> Therapy)</span></code></pre></div>
<pre><code>## $emmeans
##  Therapy emmean   SE df lower.CL upper.CL
##  Control   73.8 4.68 26     64.1     83.4
##  PA        64.6 4.68 26     55.0     74.2
##  SSRI      56.9 4.68 26     47.3     66.5
##  VT        39.7 5.40 26     28.6     50.8
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast       estimate   SE df t.ratio p.value
##  Control - PA       9.12 6.62 26   1.379  0.5230
##  Control - SSRI    16.88 6.62 26   2.551  0.0752
##  Control - VT      34.08 7.15 26   4.770  0.0003
##  PA - SSRI          7.75 6.62 26   1.171  0.6497
##  PA - VT           24.96 7.15 26   3.493  0.0088
##  SSRI - VT         17.21 7.15 26   2.408  0.1004
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p>Mit dem <code>pairwise</code> Argument sagen wir der <code>emmeans()</code> Funktion zwischen welchen Gruppen die Mittelwertsvergleiche durchgeführt werden sollen.</p>
<p>Der Output der <code>emmeans()</code> Funktion hat 2 Teile</p>
<ul>
<li>$emmeans (oberer Teil: hier werden praktischerweise die verglichenen Mittelwerte noch einmal ausgerechnet)</li>
<li>$contrasts (unterer Teil: hier werden die Ergebnisse der Post-hoc Tests gezeigt)</li>
</ul>
<p>Die Interpretation des Ergebnisses ist uns bereits bekannt. Jeder Vergleich erhält einen t-Wert und einen p-Wert, anhand dessen wir ablesen können, ob der Gruppenunterschied signifikant war.</p>
<p>Der Mittelwert der Gruppe VT war signifikant niedriger als der in der Kontrollgruppe <span class="math inline">\((t_{26}=4.77,p=.0003)\)</span> und als der in der PA Gruppe <span class="math inline">\((t_{26}=3.49,p=.0088)\)</span>. Die anderen Vergleiche waren nicht signifikant.</p>
<div id="korrektur-für-multiples-testen" class="section level4 hasAnchor" number="15.1.5.1">
<h4><span class="header-section-number">15.1.5.1</span> Korrektur für multiples Testen<a href="anova.html#korrektur-für-multiples-testen" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Nun haben wir im Abschnitt über die <span class="math inline">\(\alpha\)</span>-Fehler Kumulierung bereits erfahren, dass das Durchführen vieler Vergleiche problematisch sein kann, da es die Wahrscheinlichkeit erhöht, einen Fehler 1. Art zu begehen.</p>
<p>Post-hoc Tests lösen dieses Problem durch eine Korrektur des p-Werts. Je mehr Vergleiche gemacht werden, desto mehr wird er nach oben korrigiert. Automatisch wendet <code>emmeans()</code> die sogenannte Tukey-Korrektur an (ganz unten im Output sichtbar).</p>
<p>Zwei weitere Korrekturen sind gängig, die etwas strengere Bonferroni-Korrektur und die etwas weniger strenge Benjamini-Hochberg Korrektur (auch false-dicovery-rate Korrektur - FDR genannt).</p>
<p>Wollen wir die Korrekturmethode ändern, lässt sich das leicht über das <code>adjust</code> Argument erreichen:</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="anova.html#cb437-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod, pairwise <span class="sc">~</span> Therapy, <span class="at">adjust =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## $emmeans
##  Therapy emmean   SE df lower.CL upper.CL
##  Control   73.8 4.68 26     64.1     83.4
##  PA        64.6 4.68 26     55.0     74.2
##  SSRI      56.9 4.68 26     47.3     66.5
##  VT        39.7 5.40 26     28.6     50.8
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast       estimate   SE df t.ratio p.value
##  Control - PA       9.12 6.62 26   1.379  1.0000
##  Control - SSRI    16.88 6.62 26   2.551  0.1019
##  Control - VT      34.08 7.15 26   4.770  0.0004
##  PA - SSRI          7.75 6.62 26   1.171  1.0000
##  PA - VT           24.96 7.15 26   3.493  0.0104
##  SSRI - VT         17.21 7.15 26   2.408  0.1405
## 
## P value adjustment: bonferroni method for 6 tests</code></pre>
<p>Wir sehen, dass die etwas strengere Bonferroni-Korrektur die p-Werte vergleichsweise höher werden lässt, als mit der Tukey-Korrektur. Es ist also für den p-Wert schwieriger, unter das Signifikanznivea <span class="math inline">\(\alpha=.05\)</span> zu kommen.</p>
<p>Mit der Benjamini-Hochberg Korrektur sind die Anpassungen weniger streng:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="anova.html#cb439-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod, pairwise <span class="sc">~</span> Therapy, <span class="at">adjust =</span> <span class="st">&quot;fdr&quot;</span>)</span></code></pre></div>
<pre><code>## $emmeans
##  Therapy emmean   SE df lower.CL upper.CL
##  Control   73.8 4.68 26     64.1     83.4
##  PA        64.6 4.68 26     55.0     74.2
##  SSRI      56.9 4.68 26     47.3     66.5
##  VT        39.7 5.40 26     28.6     50.8
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast       estimate   SE df t.ratio p.value
##  Control - PA       9.12 6.62 26   1.379  0.2155
##  Control - SSRI    16.88 6.62 26   2.551  0.0340
##  Control - VT      34.08 7.15 26   4.770  0.0004
##  PA - SSRI          7.75 6.62 26   1.171  0.2520
##  PA - VT           24.96 7.15 26   3.493  0.0052
##  SSRI - VT         17.21 7.15 26   2.408  0.0351
## 
## P value adjustment: fdr method for 6 tests</code></pre>
</div>
</div>
</div>
<div id="mehrfaktorielle-anova" class="section level2 hasAnchor" number="15.2">
<h2><span class="header-section-number">15.2</span> Mehrfaktorielle ANOVA<a href="anova.html#mehrfaktorielle-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Mit der ANOVA haben wir die Möglichkeit, die Effekte mehrere UVs (Faktoren) auf die AV zu untersuchen.</p>
<p>Wir prüfen dann letztlich 3 Hypothesen (bei 2 UVs)</p>
<ul>
<li>Haupteffekt des 1. Faktors</li>
<li>Haupteffekt des 2. Faktors</li>
<li>Interaktionseffekt beider Faktoren</li>
</ul>
<p>In unserem Beispiel könnte es interessant sein, zusätzlich zur erhaltenen Therapie zu berücksichtigen, welche Diagnose die Patienten hatten.</p>
<p>Unsere Fragestellung würde sich um 2 weitere Aspekte erweitern:</p>
<ol style="list-style-type: decimal">
<li><em>Nach welcher Therapie haben die Patient:innen die schwächsten Symptome?</em> (hatten wir bereits - Haupteffekt Therapie)</li>
<li><em>Welche Diagnose hatte die schwächsten Symptome?</em> (Haupteffekt Diagnose)</li>
<li><em>Gibt es, je nachdem welche Diagnose die Patienten hatten, Unterschiede in der Wirksamkeit der Therapie?</em> (Interaktioniseffekt)</li>
</ol>
<div id="deskriptive-einordnung-5" class="section level3 hasAnchor" number="15.2.1">
<h3><span class="header-section-number">15.2.1</span> Deskriptive Einordnung<a href="anova.html#deskriptive-einordnung-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Zunächst können wir uns die Deskriptivstatistiken innerhalb der Gruppen einmal anschauen:</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="anova.html#cb441-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describeBy</span>(Symptoms <span class="sc">~</span> Therapy <span class="sc">*</span> Diagnosis, <span class="at">data =</span> therapy)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## Therapy: Control
## Diagnosis: Angst
##          vars n mean   sd median trimmed  mad min max range  skew kurtosis   se
## Symptoms    1 5 71.2 8.41     70    71.2 7.41  59  82    23 -0.17    -1.56 3.76
## ------------------------------------------------------------ 
## Therapy: PA
## Diagnosis: Angst
##          vars n mean    sd median trimmed   mad min max range skew kurtosis
## Symptoms    1 4   66 18.57   63.5      66 17.05  47  90    43 0.25    -2.01
##            se
## Symptoms 9.28
## ------------------------------------------------------------ 
## Therapy: SSRI
## Diagnosis: Angst
##          vars n  mean    sd median trimmed  mad min max range  skew kurtosis
## Symptoms    1 4 65.75 12.09     66   65.75 12.6  51  80    29 -0.04    -1.96
##            se
## Symptoms 6.05
## ------------------------------------------------------------ 
## Therapy: VT
## Diagnosis: Angst
##          vars n mean    sd median trimmed   mad min max range skew kurtosis  se
## Symptoms    1 2 24.5 13.44   24.5    24.5 14.08  15  34    19    0    -2.75 9.5
## ------------------------------------------------------------ 
## Therapy: Control
## Diagnosis: Depression
##          vars n mean   sd median trimmed mad min max range  skew kurtosis se
## Symptoms    1 3   78 6.93     82      78   0  70  82    12 -0.38    -2.33  4
## ------------------------------------------------------------ 
## Therapy: PA
## Diagnosis: Depression
##          vars n  mean   sd median trimmed  mad min max range skew kurtosis   se
## Symptoms    1 4 63.25 8.26     62   63.25 7.41  55  74    19 0.27    -2.02 4.13
## ------------------------------------------------------------ 
## Therapy: SSRI
## Diagnosis: Depression
##          vars n mean   sd median trimmed  mad min max range skew kurtosis   se
## Symptoms    1 4   48 7.53     48      48 8.15  39  57    18    0    -1.98 3.76
## ------------------------------------------------------------ 
## Therapy: VT
## Diagnosis: Depression
##          vars n  mean    sd median trimmed  mad min max range skew kurtosis
## Symptoms    1 4 47.25 15.52     45   47.25 12.6  31  68    37  0.3     -1.9
##            se
## Symptoms 7.76</code></pre>
<p>Der <code>*</code> zwischen den Faktoren bedeutet “Interaktion” und führt dazu, dass alle Stufenkombinationen der beiden Variablen exploriert werden.</p>
<p>Die Gruppenunterschiede lassen sich auch graphisch gut darstellen:</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="anova.html#cb443-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> therapy, <span class="fu">aes</span>(<span class="at">x =</span> Therapy, <span class="at">y =</span> Symptoms, <span class="at">colour =</span> Diagnosis)) <span class="sc">+</span></span>
<span id="cb443-2"><a href="anova.html#cb443-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se,  <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>) <span class="sc">+</span></span>
<span id="cb443-3"><a href="anova.html#cb443-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">fun =</span> mean) </span></code></pre></div>
<p><img src="CFH_R_bookdown_files/figure-html/unnamed-chunk-269-1.png" width="672" /></p>
</div>
<div id="berechnung-der-anova-1" class="section level3 hasAnchor" number="15.2.2">
<h3><span class="header-section-number">15.2.2</span> Berechnung der ANOVA<a href="anova.html#berechnung-der-anova-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="berechnung-mittels-lm-1" class="section level4 hasAnchor" number="15.2.2.1">
<h4><span class="header-section-number">15.2.2.1</span> Berechnung mittels <code>lm()</code><a href="anova.html#berechnung-mittels-lm-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Die Vorgehensweise ist dieselbe wie bei der einfaktoriellen ANOVA. Die Formel wird lediglich durch die Interaktion mit der 2. UV erweitert.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="anova.html#cb444-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">=</span> <span class="fu">lm</span>(Symptoms <span class="sc">~</span> Therapy <span class="sc">*</span> Diagnosis, <span class="at">data =</span> therapy)</span>
<span id="cb444-2"><a href="anova.html#cb444-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Symptoms
##                   Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Therapy            3 4242.4 1414.14  9.9411 0.0002439 ***
## Diagnosis          1    0.6    0.60  0.0042 0.9487141    
## Therapy:Diagnosis  3 1421.4  473.81  3.3308 0.0381543 *  
## Residuals         22 3129.6  142.25                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Der Output der ANOVA erweitert sich im Vergleich zur einfaktoriellen ANOVA um 2 Zeilen. Die mit <code>Therapy</code> und <code>Diagnosis</code> betitelten Zeilen sind die Haupteffekte. Die 3. Zeile <code>Therapy:Diagnosis</code> ist der Interaktionseffekt.</p>
<p>Da wir mit der 2-faktoriellen ANOVA letztlich 3 Hypothesen prüfen, gibt es auch 3 p-Werte, die alle entweder signifikante oder nicht-signifikant sein können.</p>
</div>
<div id="berechnung-mittels-aov_ez-1" class="section level4 hasAnchor" number="15.2.2.2">
<h4><span class="header-section-number">15.2.2.2</span> Berechnung mittels <code>aov_ez()</code><a href="anova.html#berechnung-mittels-aov_ez-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Auch für die <code>aov_ez()</code> Funktion ähnelt das Vorgehen dem der einfaktoriellen ANOVA. Hier wird die Liste der UVs lediglich um den 2. Faktor erweitert, die Interaktion wird automatisch mitberechnet. Das Ergebnis ist analog zur <code>lm()</code> Funktion.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="anova.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span>
<span id="cb446-2"><a href="anova.html#cb446-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">=</span> <span class="fu">aov_ez</span>(<span class="at">dv =</span> <span class="st">&quot;Symptoms&quot;</span>, <span class="at">between =</span> <span class="fu">c</span>(<span class="st">&quot;Therapy&quot;</span>, <span class="st">&quot;Diagnosis&quot;</span>), <span class="at">id =</span> <span class="st">&quot;X&quot;</span>, <span class="at">data =</span> therapy)</span>
<span id="cb446-3"><a href="anova.html#cb446-3" aria-hidden="true" tabindex="-1"></a>mod</span></code></pre></div>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: Symptoms
##              Effect    df    MSE         F  ges p.value
## 1           Therapy 3, 22 142.25 11.60 *** .613   &lt;.001
## 2         Diagnosis 1, 22 142.25      0.25 .011    .621
## 3 Therapy:Diagnosis 3, 22 142.25    3.33 * .312    .038
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="interpretation-1" class="section level3 hasAnchor" number="15.2.3">
<h3><span class="header-section-number">15.2.3</span> Interpretation<a href="anova.html#interpretation-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Die beiden Haupteffekte und der Interaktionseffekt können einzeln interpretiert werden. Wir gehen der Reihe nach:</p>
<div id="haupteffekt-1" class="section level4 hasAnchor" number="15.2.3.1">
<h4><span class="header-section-number">15.2.3.1</span> Haupteffekt 1<a href="anova.html#haupteffekt-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Der Haupteffekt von <code>Therapy</code> spiegelt im Wesentlichen das Ergebnis wieder, welches wir bereits von der einfaktoriellen ANOVA kennen. Es handelt sich um den Effekt der Therapie, wenn man den Effekt der 2. UV (Diagnosis) außer Acht lässt.</p>
<p>Der Haupteffekt ist signifikant bei <span class="math inline">\(F_{(3,22)}=9.94, p&lt;.001\)</span>. Wir können schlussfolgern, dass es einen Unterschied zwischen den Diagnosen gibt. Wo die Unterschiede genau liegenm, können wir mit den Post-hoc Tests bestimmen, wie oben bereits geschehen.</p>
</div>
<div id="haupteffekt-2" class="section level4 hasAnchor" number="15.2.3.2">
<h4><span class="header-section-number">15.2.3.2</span> Haupteffekt 2<a href="anova.html#haupteffekt-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Der Haupteffekt von <code>Diagnosis</code> ist nichts anderes als ein unabhängiger t-Test. Es handelt sich um den Effekt der Diagnose, wenn man den Effekt der 1. UV (Therapy) außer Acht lässt. Dieser Haupteffekt ist nicht signifikant <span class="math inline">\(F_{(1,22)}=0.004, p&lt;.949\)</span>. Über alle Therapien hinweg scheint es keinen Unterschied in der Symptomatik der Patient:innen mit Depressionen und Angststörungen zu geben.</p>
</div>
<div id="interaktionseffekt" class="section level4 hasAnchor" number="15.2.3.3">
<h4><span class="header-section-number">15.2.3.3</span> Interaktionseffekt<a href="anova.html#interaktionseffekt" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Der Interaktionseffekt von <code>Therapy * Diagnosis</code> prüft, ob der Effekt der Therapie in beiden Diagnosen unterschiedlich wirkt.
Er ist somit eine Möglichkeit den “kombinierten Effekt” der beiden Variablen zu prüfen.</p>
<p>Der Interaktionseffekt ist signifikant <span class="math inline">\(F_{(3,22)}=3.33, p&lt;.038\)</span>. Entsprechend scheinen die Patient:innen nach den Therapien unterschiedlich wenige Symptome zu haben, je nachdem welche Diagnose sie hatten.</p>
<p>Um diesen Effekt inhaltlich zu verstehen, empfiehlt sich ein Blick auf die Graphik, in Kombination mit Post-Hoc Tests.</p>
</div>
</div>
<div id="post-hoc-tests-1" class="section level3 hasAnchor" number="15.2.4">
<h3><span class="header-section-number">15.2.4</span> Post-hoc Tests<a href="anova.html#post-hoc-tests-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Zum Verständnis der Effekte führen wir Post-Hoc Tests durch. Allerdings wollen wir uns den Effekt der Therapie diesmal getrennt für die Diagnosen ansehen.</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="anova.html#cb448-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb448-2"><a href="anova.html#cb448-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod, pairwise <span class="sc">~</span> Therapy<span class="sc">|</span>Diagnosis)</span></code></pre></div>
<pre><code>## $emmeans
## Diagnosis = Angst:
##  Therapy emmean   SE df lower.CL upper.CL
##  Control   71.2 5.33 22    60.14     82.3
##  PA        66.0 5.96 22    53.63     78.4
##  SSRI      65.8 5.96 22    53.38     78.1
##  VT        24.5 8.43 22     7.01     42.0
## 
## Diagnosis = Depression:
##  Therapy emmean   SE df lower.CL upper.CL
##  Control   78.0 6.89 22    63.72     92.3
##  PA        63.2 5.96 22    50.88     75.6
##  SSRI      48.0 5.96 22    35.63     60.4
##  VT        47.2 5.96 22    34.88     59.6
## 
## Confidence level used: 0.95 
## 
## $contrasts
## Diagnosis = Angst:
##  contrast       estimate    SE df t.ratio p.value
##  Control - PA       5.20  8.00 22   0.650  0.9144
##  Control - SSRI     5.45  8.00 22   0.681  0.9031
##  Control - VT      46.70  9.98 22   4.680  0.0006
##  PA - SSRI          0.25  8.43 22   0.030  1.0000
##  PA - VT           41.50 10.33 22   4.018  0.0030
##  SSRI - VT         41.25 10.33 22   3.994  0.0032
## 
## Diagnosis = Depression:
##  contrast       estimate    SE df t.ratio p.value
##  Control - PA      14.75  9.11 22   1.619  0.3889
##  Control - SSRI    30.00  9.11 22   3.293  0.0162
##  Control - VT      30.75  9.11 22   3.376  0.0134
##  PA - SSRI         15.25  8.43 22   1.808  0.2962
##  PA - VT           16.00  8.43 22   1.897  0.2580
##  SSRI - VT          0.75  8.43 22   0.089  0.9997
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p>Wir sehen, dass die Symptome nach SSRI insbesondere in der Gruppe der depressiven Patient:innen reduziert sind. Zudem sind die Symtome nach der VT deutlich reduziert (insbesondere bei Angststörungen).</p>
<p>Dies führt dazu, dass die VT (in dieser Stichprobe) in der Behandlung von Angststörungen der Kontrollgruppe <span class="math inline">\((t_{(22)}=4.68, p&lt;.001)\)</span>, der Psychoanalyse <span class="math inline">\((t_{(22)}=4.02, p=.003)\)</span> und den SSRI <span class="math inline">\((t_{(22)}=3.99, p=.003)\)</span> überlegen war. In der Behandlung von Angststörungen waren sowohl SSRI <span class="math inline">\((t_{(22)}=3.29, p=.016)\)</span> als auch VT <span class="math inline">\((t_{(22)}=3.38, p=.013)\)</span> besser als die Kontrollgruppe, unterschieden sich jedoch nicht signifikant von der Psychoanalyse und auch nicht voneinander.</p>
</div>
</div>
<div id="prüfen-der-voraussetzungen-von-anovas" class="section level2 hasAnchor" number="15.3">
<h2><span class="header-section-number">15.3</span> Prüfen der Voraussetzungen von ANOVAs<a href="anova.html#prüfen-der-voraussetzungen-von-anovas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Wie alle statistischen Modelle haben ANOVAs eine Reihe von Annahmen, die für gültige Schlussfolgerungen gelten sollten. Diese Annahmen sind:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Beobachtungen sind i.i.d.:</strong> i.i.d. steht für “unabhängig und identisch verteilt”. Unabhängig bedeutet, dass die bedingten Beobachtungen (d.h. Residuen) unabhängig voneinander sind (d.h. das Wissen des Wertes eines Residuums erlaubt keine Rückschlüsse auf den Wert eines anderen Residuums). Identisch verteilt bedeutet, dass alle Beobachtungen durch denselben Daten-generierenden Prozess erzeugt werden.</p></li>
<li><p><strong>Homogenität der Varianzen:</strong> Die Varianzen über alle Gruppen (Zellen) der zwischen-Subjekt-Effekte sind gleich.</p></li>
<li><p><strong>Sphärizität:</strong> Bei innerhalb-Subjekt-Effekten ist die Sphärizität die Bedingung, dass die Varianzen der Unterschiede zwischen allen möglichen Paaren von innerhalb-Subjekt-Bedingungen (d.h. Levels der unabhängigen Variablen) gleich sind. Dies kann als eine innerhalb-Subjekt-Version der Homogenität der Varianzen-Annahme betrachtet werden.</p></li>
<li><p><strong>Normalverteilung der Residuen:</strong> Die Fehler, die für die Schätzung des Fehlerterms (MSE) verwendet werden, sind normalverteilt.</p></li>
</ol>
<p>Die wichtigste Annahme ist im Allgemeinen die i.i.d.-Annahme (d.h. wenn sie nicht erfüllt ist, sind die Schlussfolgerungen wahrscheinlich ungültig), insbesondere der unabhängige Teil. Diese Annahme kann nicht empirisch getestet werden, sondern muss auf konzeptuellen oder logischen Gründen beruhen. Zum Beispiel stammen in einem idealen vollständig zwischen den Probanden durchgeführten Design jede Beobachtung von einem anderen Probanden, der zufällig aus einer Population ausgewählt wird, so dass wir wissen, dass alle Beobachtungen unabhängig sind. Oft sammeln wir jedoch mehrere Beobachtungen von demselben Probanden in einem innerhalb der Probanden oder wiederholten Messungen-Design. Um sicherzustellen, dass die i.i.d.-Annahme in diesem Fall erfüllt ist, müssen wir eine ANOVA mit innerhalb der Probanden Faktoren angeben. Wenn wir jedoch einen Datensatz mit mehreren Quellen von Nicht-Unabhängigkeit haben - wie Teilnehmern und Items - können ANOVA-Modelle nicht verwendet werden, sondern wir müssen ein gemischtes Modell verwenden.</p>
<p>Die anderen Annahmen können empirisch getestet werden, entweder graphisch oder mit statistischen Annahmetests. Es gibt jedoch unterschiedliche Meinungen darüber, wie nützlich statistische Annahmetests sind, wenn sie automatisch für jede ANOVA durchgeführt werden. Obwohl dies in einigen Statistikbüchern vertreten wird, besteht die Gefahr, dass die statistische Analyse auf ein “Kochbuch” oder “Flussdiagramm” reduziert wird. Die Datenanalyse in der Realität ist oft komplexer als solche einfachen Regeln. Es ist daher oft produktiver, die Daten mit Hilfe von deskriptiven Statistiken und grafischen Darstellungen zu erkunden. Diese Datenexploration sollte es ermöglichen, zu beurteilen, ob die anderen ANOVA-Annahmen in ausreichendem Maße erfüllt sind. Zum Beispiel ermöglicht es das Plotten der ANOVA-Ergebnisse mit afex_plot und einer vernünftigen Darstellung der einzelnen Datenpunkte oft, sowohl die Homogenität der Varianz als auch die Normalverteilung der Residuenannahme zu beurteilen.</p>
<p>Lassen Sie uns nun alle drei empirisch testbaren Annahmen im Detail betrachten. ANOVAs sind oft robust gegen leichte Verletzungen der Annahme der Homogenität der Varianzen. Wenn diese Annahme jedoch deutlich verletzt ist, haben wir etwas Wichtiges über die Daten gelernt, nämlich Varianzheterogenität, die weitere Untersuchungen erfordert. Einige weitere statistische Lösungen werden unten diskutiert.</p>
<p>Wenn das Hauptziel einer ANOVA darin besteht, zu sehen, ob bestimmte Effekte signifikant sind oder nicht, dann ist die Annahme der Normalverteilung der Residuen nur für kleine Stichproben erforderlich, dank des zentralen Grenzwertsatzes. Wie von Lumley et al. (2002) gezeigt, sind selbst extreme Verletzungen der Normalitätsannahmen bei Stichproben von ein paar hundert Probanden unproblematisch. Daher sind leichte Verletzungen dieser Annahme unproblematisch.</p>
<p>Eine angemessene explorative Datenanalyse oft besser ist als die blindes Anwenden von statistischen Annahmetests. Dennoch sind Annahmetests natürlich ein wichtiges Werkzeug im statistischen Werkzeugkasten und können in vielen Situationen hilfreich sein.</p>
<div id="testen-der-empirisch-testbaren-annahmen" class="section level3 hasAnchor" number="15.3.1">
<h3><span class="header-section-number">15.3.1</span> Testen der empirisch testbaren Annahmen<a href="anova.html#testen-der-empirisch-testbaren-annahmen" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>afex</code>verfügt über eine Reihe von integrierten Funktionen, um bei der Überprüfung der Annahmen des ANOVA-Designs zu helfen.</p>
<ul>
<li>Die Varianzen über alle Gruppen (Zellen) der zwischen-subjektiven Effekte sind gleich. Dies kann mit performance::check_homogeneity() getestet werden.</li>
<li>Sphärizität: Für innerhalb-subjektive Effekte ist die Sphärizität die Bedingung, bei der die Varianzen der Unterschiede zwischen allen möglichen Paaren von innerhalb-subjektiven Bedingungen (d.h. Stufen der unabhängigen Variable) gleich sind. Dies kann als eine innerhalb-subjektive Version der Homogenität der Varianzen betrachtet werden und kann mit performance::check_sphericity() getestet werden.</li>
<li>Normalität der Residuen: Die für die Schätzung des Fehlerterms (MSE) verwendeten Fehler sind normal verteilt. Dies kann mit performance::check_normality() abgeleitet werden.</li>
</ul>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="anova.html#cb450-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span>
<span id="cb450-2"><a href="anova.html#cb450-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co"># für die Voraussetzungsprüfung</span></span></code></pre></div>
</div>
<div id="homogenität-der-varianzen" class="section level3 hasAnchor" number="15.3.2">
<h3><span class="header-section-number">15.3.2</span> Homogenität der Varianzen:<a href="anova.html#homogenität-der-varianzen" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Diese Annahme besagt für Zwischen-Gruppen-Designs, dass die Fehler innerhalb der Gruppen eine gemeinsame Varianz um den Mittelwert der Gruppe aufweisen.</p>
<div id="test" class="section level4 hasAnchor" number="15.3.2.1">
<h4><span class="header-section-number">15.3.2.1</span> Test<a href="anova.html#test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dies kann mit dem Levene-Test getestet werden:</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="anova.html#cb451-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(obk.long, <span class="at">package =</span> <span class="st">&quot;afex&quot;</span>)</span>
<span id="cb451-2"><a href="anova.html#cb451-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb451-3"><a href="anova.html#cb451-3" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;value&quot;</span>, obk.long, </span>
<span id="cb451-4"><a href="anova.html#cb451-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">between =</span> <span class="fu">c</span>(<span class="st">&quot;treatment&quot;</span>, <span class="st">&quot;gender&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: More than one observation per design cell, aggregating data using `fun_aggregate = mean`.
## To turn off this warning, pass `fun_aggregate = mean` explicitly.</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: treatment, gender</code></pre>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="anova.html#cb454-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_homogeneity</span>(mod)</span></code></pre></div>
<pre><code>## OK: There is not clear evidence for different variances across groups (Levene&#39;s Test, p = 0.350).</code></pre>
<p>Diese Ergebnisse deuten darauf hin, dass die Homogenität nicht signifikant verletzt ist.</p>
</div>
<div id="maßnahmen-wenn-vorraussetzung-verletzt" class="section level4 hasAnchor" number="15.3.2.2">
<h4><span class="header-section-number">15.3.2.2</span> Maßnahmen wenn Vorraussetzung verletzt<a href="anova.html#maßnahmen-wenn-vorraussetzung-verletzt" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ANOVAs sind im Allgemeinen robust gegenüber “leichter” Heteroskedastizität, aber es gibt verschiedene andere Methoden (die in <code>afex</code> nicht verfügbar sind), um robuste Fehlerabschätzungen zu erhalten.</p>
<p>Eine weitere Alternative besteht darin, diese Annahme ganz aufzugeben und Permutationstests (z.B. mit <code>permuco</code>) oder Bootstrap-Schätzungen (z.B. mit <code>boot</code>) zu verwenden.</p>
</div>
</div>
<div id="sphärizität" class="section level3 hasAnchor" number="15.3.3">
<h3><span class="header-section-number">15.3.3</span> Sphärizität:<a href="anova.html#sphärizität" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="test-1" class="section level4 hasAnchor" number="15.3.3.1">
<h4><span class="header-section-number">15.3.3.1</span> Test<a href="anova.html#test-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Wir können check_sphericity() verwenden, um den Mauchly-Test auf Sphärizität durchzuführen:</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="anova.html#cb456-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;fhch2010&quot;</span>, <span class="at">package =</span> <span class="st">&quot;afex&quot;</span>)</span>
<span id="cb456-2"><a href="anova.html#cb456-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb456-3"><a href="anova.html#cb456-3" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;log_rt&quot;</span>, fhch2010,</span>
<span id="cb456-4"><a href="anova.html#cb456-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">between =</span> <span class="st">&quot;task&quot;</span>, </span>
<span id="cb456-5"><a href="anova.html#cb456-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">within =</span> <span class="fu">c</span>(<span class="st">&quot;density&quot;</span>, <span class="st">&quot;frequency&quot;</span>, <span class="st">&quot;length&quot;</span>, <span class="st">&quot;stimulus&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: More than one observation per design cell, aggregating data using `fun_aggregate = mean`.
## To turn off this warning, pass `fun_aggregate = mean` explicitly.</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: task</code></pre>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="anova.html#cb459-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_sphericity</span>(mod)</span></code></pre></div>
<pre><code>## Warning in summary.Anova.mlm(object$Anova, multivariate = FALSE): HF eps &gt; 1
## treated as 1</code></pre>
<pre><code>## Warning: Sphericity violated for: 
##  - length:stimulus (p = 0.021)
##  - task:length:stimulus (p = 0.021).</code></pre>
<p>Wir können sehen, dass beide Fehlerterme der Länge:Reiz und Aufgabe:Länge:Reiz-Interaktionen die Annahme der Sphärizität bei <span class="math inline">\(p = 0.021\)</span> signifikant verletzen. Beachten Sie, dass Aufgabe als Faktor zwischen den Probanden gilt und dass beide Interaktionsterme denselben Fehlerterm teilen!</p>
</div>
<div id="maßnahmen-wenn-vorraussetzung-verletzt-1" class="section level4 hasAnchor" number="15.3.3.2">
<h4><span class="header-section-number">15.3.3.2</span> Maßnahmen wenn Vorraussetzung verletzt<a href="anova.html#maßnahmen-wenn-vorraussetzung-verletzt-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Für ANOVA-Tabellen kann eine Korrektur der Freiheitsgrade verwendet werden - afex bietet sowohl die Greenhouse-Geisser (die standardmäßig verwendet wird) als auch die Hyunh-Feldt-Korrekturen an.
Für Nachfolgekontraste mit emmeans kann ein multivariates Modell verwendet werden, das keine Sphärizität annimmt (dies wird seit afex 1.0 standardmäßig verwendet).</p>
<p>Beide können global festgelegt werden mit:</p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="anova.html#cb462-1" aria-hidden="true" tabindex="-1"></a><span class="fu">afex_options</span>(</span>
<span id="cb462-2"><a href="anova.html#cb462-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">correction_aov =</span> <span class="st">&quot;GG&quot;</span>, <span class="co"># or &quot;HF&quot;</span></span>
<span id="cb462-3"><a href="anova.html#cb462-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">emmeans_model =</span> <span class="st">&quot;multivariate&quot;</span></span>
<span id="cb462-4"><a href="anova.html#cb462-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</div>
</div>
<div id="normalverteilung-der-residuen" class="section level3 hasAnchor" number="15.3.4">
<h3><span class="header-section-number">15.3.4</span> Normalverteilung der Residuen:<a href="anova.html#normalverteilung-der-residuen" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Die Normalverteilungsannahme der Restfehler bezieht sich auf die Fehler, die die verschiedenen Fehlerterme in der ANOVA ausmachen. Obwohl der Shapiro-Wilk-Test verwendet werden kann, um von einer Normalverteilung abzuweichen, hat dieser Test tendenziell hohe Typ-I-Fehler-Raten. Stattdessen können die Restfehler visuell mit Quantil-Quantil-Plots (auch qq-Plots genannt) inspiziert werden. Zum Beispiel:</p>
<div id="test-2" class="section level4 hasAnchor" number="15.3.4.1">
<h4><span class="header-section-number">15.3.4.1</span> Test<a href="anova.html#test-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="anova.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;stroop&quot;</span>, <span class="at">package =</span> <span class="st">&quot;afex&quot;</span>)</span>
<span id="cb463-2"><a href="anova.html#cb463-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb463-3"><a href="anova.html#cb463-3" aria-hidden="true" tabindex="-1"></a>stroop1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(stroop, study <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb463-4"><a href="anova.html#cb463-4" aria-hidden="true" tabindex="-1"></a>stroop1 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(stroop1)</span>
<span id="cb463-5"><a href="anova.html#cb463-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb463-6"><a href="anova.html#cb463-6" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="st">&quot;pno&quot;</span>, <span class="st">&quot;rt&quot;</span>, stroop1,</span>
<span id="cb463-7"><a href="anova.html#cb463-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">within =</span> <span class="fu">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;congruency&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: More than one observation per design cell, aggregating data using `fun_aggregate = mean`.
## To turn off this warning, pass `fun_aggregate = mean` explicitly.</code></pre>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="anova.html#cb465-1" aria-hidden="true" tabindex="-1"></a>is_norm <span class="ot">&lt;-</span> <span class="fu">check_normality</span>(mod)</span>
<span id="cb465-2"><a href="anova.html#cb465-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb465-3"><a href="anova.html#cb465-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(is_norm)</span></span></code></pre></div>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="anova.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(is_norm, type = &quot;qq&quot;)</span></span></code></pre></div>
<p>Wenn die Residuen normalverteilt wären, würden sie in der Nähe der diagonalen Linie liegen und innerhalb der 95%-Konfidenzbänder um die qq-Linie fallen.</p>
<p>Wir können das Diagramm weiter verbessern, indem wir den Trend entfernen und nicht den erwarteten Quantilwert, sondern die Abweichung vom erwarteten Quantilwert anzeigen, was dazu beitragen kann, visuelle Verzerrungen zu reduzieren.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="anova.html#cb467-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(is_norm, type = &quot;qq&quot;, detrend = TRUE)</span></span></code></pre></div>
</div>
<div id="maßnahmen-wenn-vorraussetzung-verletzt-2" class="section level4 hasAnchor" number="15.3.4.2">
<h4><span class="header-section-number">15.3.4.2</span> Maßnahmen wenn Vorraussetzung verletzt<a href="anova.html#maßnahmen-wenn-vorraussetzung-verletzt-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Wie bei der Annahme der Homogenität der Varianzen können wir auf Permutationstests für ANOVA-Tabellen und Bootstrap-Schätzungen / Kontraste zurückgreifen.</p>
<p>Eine weitere beliebte Lösung besteht darin, eine monotone Transformation der abhängigen Variablen anzuwenden. Dies sollte nicht leichtfertig getan werden, da es die Interpretierbarkeit der Ergebnisse (von der beobachteten Skala zur transformierten Skala) verändert. Glücklicherweise ist es üblich, Reaktionszeiten zu logarithmieren, was wir leicht tun können:</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="anova.html#cb468-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="st">&quot;pno&quot;</span>, <span class="st">&quot;rt&quot;</span>, stroop1,</span>
<span id="cb468-2"><a href="anova.html#cb468-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">transformation =</span> <span class="st">&quot;log&quot;</span>,</span>
<span id="cb468-3"><a href="anova.html#cb468-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">within =</span> <span class="fu">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;congruency&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: More than one observation per design cell, aggregating data using `fun_aggregate = mean`.
## To turn off this warning, pass `fun_aggregate = mean` explicitly.</code></pre>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="anova.html#cb470-1" aria-hidden="true" tabindex="-1"></a>is_norm <span class="ot">&lt;-</span> <span class="fu">check_normality</span>(mod)</span>
<span id="cb470-2"><a href="anova.html#cb470-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb470-3"><a href="anova.html#cb470-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(is_norm, type = &quot;qq&quot;, detrend = TRUE)</span></span></code></pre></div>
<p>Sehr gut - nach der Transformation weichen die Residuen (auf der logarithmischen Skala) nicht mehr als erwartet von Fehlern ab, die aus einer normalverteilten Verteilung gezogen wurden (sie sind größtenteils innerhalb der 95%-Konfidenzintervalle enthalten)!</p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
Cohen, Jacob. 1988. <span>“Statistical Power Analysis for the Behavioral Sciences. Lawrence Erlbaum Associates.”</span> <em>Hillsdale, NJ</em>, 20–26.
</div>
<div class="csl-entry">
———. 1992. <span>“Quantitative Methods in Psychology: A Power Primer.”</span> In <em>Psychological Bulletin</em>. Citeseer.
</div>
<div class="csl-entry">
Ellis, Paul D. 2010. <em>The Essential Guide to Effect Sizes: Statistical Power, Meta-Analysis, and the Interpretation of Research Results</em>. Cambridge university press.
</div>
<div class="csl-entry">
Hedges, Larry V, and Ingram Olkin. 2014. <em>Statistical Methods for Meta-Analysis</em>. Academic press.
</div>
<div class="csl-entry">
Levene, Howard. 1960. <span>“Robust Tests for Equality of Variances. Contributions to Probability and Statistics (1960).”</span>
</div>
<div class="csl-entry">
Tomczak, Maciej, and Ewa Tomczak. 2014. <span>“The Need to Report Effect Size Estimates Revisited. An Overview of Some Recommended Measures of Effect Size.”</span> <em>Trends in Sport Sciences</em> 1 (21): 19–25.
</div>
</div>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="einfache-hypothesentests.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CFH_R_bookdown.pdf", "CFH_R_bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
